spring:
  application:
    name: CarService
  thymeleaf:
     check-template-location: true
     cache: false
     prefix: file:./src/main/resources/templates/
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: create-drop
    open-in-view: 'false'
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 'root1'
    username: 'root'
    url: jdbc:mysql://localhost:3306/carServiceApp?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
server:
  port: 8080

orders:
  api:
    baseurl: "http://localhost:8081"

